<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AssemblyName>TestMining.Platform.Host</AssemblyName>
    <RootNamespace>TestMining.Platform.Host</RootNamespace>
    <Product>Test Mining Platform</Product>
    <RepositoryUrl>https://github.com/ReleasedGroup/2EndSquaredTesting</RepositoryUrl>
  </PropertyGroup>

</Project>
